
tests:
	# symfony-skeleton
	./symfony skeleton 3.4
	./symfony skeleton 4.3
	./symfony skeleton 4.4
	#./symfony skeleton 5.0

	# website-skeleton
	./symfony website-skeleton 3.4
	./symfony website-skeleton 4.3
	./symfony website-skeleton 4.4
	#./symfony website-skeleton 5.0

	# symfony-framework
	#./symfony framework-standard-edition  3.4

	# specific
	cd ukenpachi && composer install --no-interaction
