version: 2.1

orbs:
    php:
        executors:
            composer:
                docker:
                    - image: composer
            phpstan:
                docker:
                    - image: phpstan/phpstan:latest
            php-cs-fixer:
                docker:
                    - image: herloct/php-cs-fixer:latest
        jobs:
            install:
                executor: composer
                working_directory: ~/project
                steps:
                  - checkout
                  - run: composer install
                  - persist_to_workspace:
                      root: ~/
                      paths:
                        - project
                  - run: cd ~/project/tests && make tests
            phpstan:
                executor: phpstan
                working_directory: ~/project
                steps:
                    - attach_workspace:
                        at: ~/
                    - run: phpstan analyse --level 5 Services
            php-cs-fixer:
                executor: php-cs-fixer
                working_directory: ~/project
                steps:
                    - run: php-cs-fixer fix --dry-run --diff ~/project
workflows:
    build_and_test:
        jobs:
            - php/install
            - php/phpstan:
                requires:
                  - php/install
            - php/php-cs-fixer:
                requires:
                  - php/install
