parameters:
    cloudflare.api_token: some-cloudflare-api_token

services:
    Gpenverne\CloudflareBundle\Services\CloudflareService:
        public: true
        arguments: ["%cloudflare.api_token%"]

    cloudflare.service:
        alias: Gpenverne\CloudflareBundle\Services\CloudflareService
        public: true
        deprecated: ~
